apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: r85qllm74-nodejs 
  janus-idp.io/tekton: r85qllm74-nodejs
  backstage.io/kubernetes-id: r85qllm74-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: r85qllm74-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  